### ISSUE TITLE
hmmm, a question of install.sh

### ISSUE THREAD

**Issue by snowman** [anmoljagetia/dotfiles#5]
What's the funtionality of this line in your file `install.sh`
https://github.com/anmoljagetia/dotfiles/blob/4e723c2c158efbf404a035a1638e2b2a4ad3db11/install.sh#L51

**Comment by anmoljagetia** [comment]
Apologies for the late reply!

I usually keep some custom binaries in this folder. I then simply add this to my $PATH. This is done, to ensure that I can them from the command line without specifying the full paths.
