### ISSUE TITLE
Character Garbled

### ISSUE THREAD

**Issue by erikaemma** [anmoljagetia/dotfiles#6]
```
ZSH_THEME_GIT_PROMPT_DIRTY="%{$fg[blue]%}❯ %{$fg[yellow]%}%{$reset_color%}"
```
Between '%{$fg[yellow]%}' and '%{$reset_color%}', the character on my Ubuntu 16.04 in China is garbled.

**Comment by anmoljagetia** [comment]
I think you need to install a programming font for the characters to show properly. Find a list of lot of nice modded fonts [here.](https://github.com/ryanoasis/nerd-fonts)
